// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_instance.sql

package repository

import (
	"context"
)

const countSecretsTotal = `-- name: CountSecretsTotal :one
SELECT COUNT(*) FROM secrets
`

func (q *Queries) CountSecretsTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSecretsTotal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getInstanceSetting = `-- name: GetInstanceSetting :one
SELECT value FROM instance_settings WHERE key = $1
`

func (q *Queries) GetInstanceSetting(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getInstanceSetting, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const upsertInstanceSetting = `-- name: UpsertInstanceSetting :exec
INSERT INTO instance_settings (key, value, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (key) DO UPDATE SET value = $2, updated_at = NOW()
`

func (q *Queries) UpsertInstanceSetting(ctx context.Context, key string, value []byte) error {
	_, err := q.db.Exec(ctx, upsertInstanceSetting, key, value)
	return err
}
