// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_analytics.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPersonalSecrets = `-- name: CountPersonalSecrets :one
SELECT COUNT(*) FROM secrets s
JOIN environments e ON e.id = s.environment_id
JOIN apps a ON a.id = e.app_id
WHERE a.workspace_type = 'personal'
`

func (q *Queries) CountPersonalSecrets(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPersonalSecrets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSecretAccessesSince = `-- name: CountSecretAccessesSince :one
SELECT COUNT(*) FROM audit_logs
WHERE action LIKE 'secrets%' AND created_at >= $1
`

func (q *Queries) CountSecretAccessesSince(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countSecretAccessesSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamsTotal = `-- name: CountTeamsTotal :one
SELECT COUNT(*) FROM teams
`

func (q *Queries) CountTeamsTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamsTotal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dailyActivity = `-- name: DailyActivity :many
SELECT
    TO_CHAR(d, 'YYYY-MM-DD') AS date,
    COALESCE(SUM(CASE WHEN action = 'secrets.create' THEN 1 ELSE 0 END), 0) AS secrets_created,
    COALESCE(SUM(CASE WHEN action LIKE 'secrets%' THEN 1 ELSE 0 END), 0) AS secrets_accessed
FROM generate_series($1::date, NOW()::date, '1 day'::interval) d
LEFT JOIN audit_logs al ON al.created_at::date = d::date
GROUP BY d
ORDER BY d ASC
`

type DailyActivityRow struct {
	Date            string      `db:"date" json:"date"`
	SecretsCreated  interface{} `db:"secrets_created" json:"secrets_created"`
	SecretsAccessed interface{} `db:"secrets_accessed" json:"secrets_accessed"`
}

func (q *Queries) DailyActivity(ctx context.Context, dollar_1 pgtype.Date) ([]DailyActivityRow, error) {
	rows, err := q.db.Query(ctx, dailyActivity, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyActivityRow{}
	for rows.Next() {
		var i DailyActivityRow
		if err := rows.Scan(&i.Date, &i.SecretsCreated, &i.SecretsAccessed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topTeamsBySecretCount = `-- name: TopTeamsBySecretCount :many
SELECT t.id, t.name, COUNT(s.id) AS count
FROM teams t
LEFT JOIN apps a ON a.workspace_id = t.id AND a.workspace_type = 'team'
LEFT JOIN environments e ON e.app_id = a.id
LEFT JOIN secrets s ON s.environment_id = e.id
GROUP BY t.id, t.name
ORDER BY count DESC
LIMIT 5
`

type TopTeamsBySecretCountRow struct {
	ID    string `db:"id" json:"id"`
	Name  string `db:"name" json:"name"`
	Count int64  `db:"count" json:"count"`
}

func (q *Queries) TopTeamsBySecretCount(ctx context.Context) ([]TopTeamsBySecretCountRow, error) {
	rows, err := q.db.Query(ctx, topTeamsBySecretCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopTeamsBySecretCountRow{}
	for rows.Next() {
		var i TopTeamsBySecretCountRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topUsersByEventCount = `-- name: TopUsersByEventCount :many
SELECT u.id, u.username AS name, COUNT(al.id) AS count
FROM users u
LEFT JOIN audit_logs al ON al.actor_id = u.id AND al.created_at >= $1
GROUP BY u.id, u.username
ORDER BY count DESC
LIMIT 5
`

type TopUsersByEventCountRow struct {
	ID    string `db:"id" json:"id"`
	Name  string `db:"name" json:"name"`
	Count int64  `db:"count" json:"count"`
}

func (q *Queries) TopUsersByEventCount(ctx context.Context, createdAt time.Time) ([]TopUsersByEventCountRow, error) {
	rows, err := q.db.Query(ctx, topUsersByEventCount, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopUsersByEventCountRow{}
	for rows.Next() {
		var i TopUsersByEventCountRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
