// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_invites.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (code, max_uses, expires_at, created_by)
VALUES ($1, $2, $3, $4) RETURNING id, created_at
`

type CreateInviteRow struct {
	ID        string    `db:"id" json:"id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, code string, maxUses *int32, expiresAt pgtype.Timestamptz, createdBy string) (CreateInviteRow, error) {
	row := q.db.QueryRow(ctx, createInvite,
		code,
		maxUses,
		expiresAt,
		createdBy,
	)
	var i CreateInviteRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deactivateInvite = `-- name: DeactivateInvite :execrows
UPDATE invites SET is_active = FALSE
WHERE id = $1 AND is_active = TRUE
`

func (q *Queries) DeactivateInvite(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateInvite, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteInvite = `-- name: DeleteInvite :execrows
DELETE FROM invites WHERE id = $1
`

func (q *Queries) DeleteInvite(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvite, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listInvites = `-- name: ListInvites :many
SELECT id, code, max_uses, use_count, is_active, expires_at, created_at
FROM invites ORDER BY created_at DESC
`

type ListInvitesRow struct {
	ID        string             `db:"id" json:"id"`
	Code      string             `db:"code" json:"code"`
	MaxUses   *int32             `db:"max_uses" json:"max_uses"`
	UseCount  int32              `db:"use_count" json:"use_count"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time          `db:"created_at" json:"created_at"`
}

func (q *Queries) ListInvites(ctx context.Context) ([]ListInvitesRow, error) {
	rows, err := q.db.Query(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitesRow{}
	for rows.Next() {
		var i ListInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.MaxUses,
			&i.UseCount,
			&i.IsActive,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
