// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, name, key_hash, key_prefix)
VALUES ($1, $2, $3, $4) RETURNING id, created_at
`

type CreateAPIKeyRow struct {
	ID        string    `db:"id" json:"id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, userID string, name string, keyHash string, keyPrefix string) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		userID,
		name,
		keyHash,
		keyPrefix,
	)
	var i CreateAPIKeyRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :execrows
DELETE FROM api_keys WHERE id = $1 AND user_id = $2
`

func (q *Queries) DeleteAPIKey(ctx context.Context, iD string, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIKey, iD, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, key_prefix, last_used, created_at
FROM api_keys WHERE user_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysRow struct {
	ID        string             `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	KeyPrefix string             `db:"key_prefix" json:"key_prefix"`
	LastUsed  pgtype.Timestamptz `db:"last_used" json:"last_used"`
	CreatedAt time.Time          `db:"created_at" json:"created_at"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, userID string) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyPrefix,
			&i.LastUsed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used = NOW() WHERE key_hash = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, keyHash string) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, keyHash)
	return err
}
