// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apps.sql

package repository

import (
	"context"
)

const createApp = `-- name: CreateApp :one
INSERT INTO apps (name, description, workspace_id, workspace_type, created_by)
VALUES ($1, $2, $3, $4, $5) RETURNING id, name, description, workspace_id, workspace_type, created_by, created_at, updated_at
`

func (q *Queries) CreateApp(ctx context.Context, name string, description *string, workspaceID string, workspaceType string, createdBy string) (App, error) {
	row := q.db.QueryRow(ctx, createApp,
		name,
		description,
		workspaceID,
		workspaceType,
		createdBy,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.WorkspaceID,
		&i.WorkspaceType,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApp = `-- name: DeleteApp :exec
DELETE FROM apps WHERE id = $1
`

func (q *Queries) DeleteApp(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteApp, id)
	return err
}

const getAppByID = `-- name: GetAppByID :one
SELECT id, name, description, workspace_id, workspace_type, created_by, created_at, updated_at FROM apps WHERE id = $1
`

func (q *Queries) GetAppByID(ctx context.Context, id string) (App, error) {
	row := q.db.QueryRow(ctx, getAppByID, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.WorkspaceID,
		&i.WorkspaceType,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersonalWorkspaceByUser = `-- name: GetPersonalWorkspaceByUser :one
SELECT id, encrypted_workspace_symmetric_key FROM personal_workspaces WHERE user_id = $1
`

type GetPersonalWorkspaceByUserRow struct {
	ID                             string `db:"id" json:"id"`
	EncryptedWorkspaceSymmetricKey string `db:"encrypted_workspace_symmetric_key" json:"encrypted_workspace_symmetric_key"`
}

func (q *Queries) GetPersonalWorkspaceByUser(ctx context.Context, userID string) (GetPersonalWorkspaceByUserRow, error) {
	row := q.db.QueryRow(ctx, getPersonalWorkspaceByUser, userID)
	var i GetPersonalWorkspaceByUserRow
	err := row.Scan(&i.ID, &i.EncryptedWorkspaceSymmetricKey)
	return i, err
}

const getPersonalWorkspaceID = `-- name: GetPersonalWorkspaceID :one
SELECT id FROM personal_workspaces WHERE user_id = $1
`

func (q *Queries) GetPersonalWorkspaceID(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, getPersonalWorkspaceID, userID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listAppsForWorkspace = `-- name: ListAppsForWorkspace :many
SELECT id, name, description, workspace_id, workspace_type, created_by, created_at, updated_at FROM apps WHERE workspace_id = $1 AND workspace_type = $2
ORDER BY created_at DESC
`

func (q *Queries) ListAppsForWorkspace(ctx context.Context, workspaceID string, workspaceType string) ([]App, error) {
	rows, err := q.db.Query(ctx, listAppsForWorkspace, workspaceID, workspaceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.WorkspaceID,
			&i.WorkspaceType,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalApps = `-- name: ListPersonalApps :many
SELECT a.id, a.name, a.description, a.workspace_id, a.workspace_type, a.created_by, a.created_at, a.updated_at FROM apps a
JOIN personal_workspaces pw ON pw.id = a.workspace_id
WHERE a.workspace_type = 'personal' AND pw.user_id = $1
ORDER BY a.created_at DESC
`

func (q *Queries) ListPersonalApps(ctx context.Context, userID string) ([]App, error) {
	rows, err := q.db.Query(ctx, listPersonalApps, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.WorkspaceID,
			&i.WorkspaceType,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamApps = `-- name: ListTeamApps :many
SELECT a.id, a.name, a.description, a.workspace_id, a.workspace_type, a.created_by, a.created_at, a.updated_at FROM apps a
JOIN team_members tm ON tm.team_id = a.workspace_id
WHERE a.workspace_type = 'team' AND tm.user_id = $1
ORDER BY a.created_at DESC
`

func (q *Queries) ListTeamApps(ctx context.Context, userID string) ([]App, error) {
	rows, err := q.db.Query(ctx, listTeamApps, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.WorkspaceID,
			&i.WorkspaceType,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApp = `-- name: UpdateApp :exec
UPDATE apps SET name = $1, description = $2, updated_at = NOW() WHERE id = $3
`

func (q *Queries) UpdateApp(ctx context.Context, name string, description *string, iD string) error {
	_, err := q.db.Exec(ctx, updateApp, name, description, iD)
	return err
}
