// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package repository

import (
	"context"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
WHERE ($1::uuid IS NULL OR actor_id = $1)
  AND ($2::text  IS NULL OR action = $2)
  AND ($3::timestamptz IS NULL OR created_at >= $3)
  AND ($4::timestamptz IS NULL OR created_at <= $4)
`

func (q *Queries) CountAuditLogs(ctx context.Context, column1 string, column2 string, column3 time.Time, column4 time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		column1,
		column2,
		column3,
		column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (actor_id, workspace_id, workspace_type, action, resource_type, resource_id, details, ip_address)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAuditLogParams struct {
	ActorID       string      `db:"actor_id" json:"actor_id"`
	WorkspaceID   string      `db:"workspace_id" json:"workspace_id"`
	WorkspaceType string      `db:"workspace_type" json:"workspace_type"`
	Action        string      `db:"action" json:"action"`
	ResourceType  *string     `db:"resource_type" json:"resource_type"`
	ResourceID    pgtype.UUID `db:"resource_id" json:"resource_id"`
	Details       []byte      `db:"details" json:"details"`
	IpAddress     *netip.Addr `db:"ip_address" json:"ip_address"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ActorID,
		arg.WorkspaceID,
		arg.WorkspaceType,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Details,
		arg.IpAddress,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT al.id, al.actor_id, al.workspace_id, al.workspace_type, al.action,
       al.resource_type, al.resource_id, al.details, al.ip_address, al.created_at,
       u.username AS actor_name
FROM audit_logs al JOIN users u ON u.id = al.actor_id
WHERE ($1::uuid IS NULL OR al.actor_id = $1)
  AND ($2::text  IS NULL OR al.action = $2)
  AND ($3::timestamptz IS NULL OR al.created_at >= $3)
  AND ($4::timestamptz IS NULL OR al.created_at <= $4)
ORDER BY al.created_at DESC
LIMIT $5 OFFSET $6
`

type ListAuditLogsParams struct {
	Column1 string    `db:"column_1" json:"column_1"`
	Column2 string    `db:"column_2" json:"column_2"`
	Column3 time.Time `db:"column_3" json:"column_3"`
	Column4 time.Time `db:"column_4" json:"column_4"`
	Limit   int32     `db:"limit" json:"limit"`
	Offset  int32     `db:"offset" json:"offset"`
}

type ListAuditLogsRow struct {
	ID            string      `db:"id" json:"id"`
	ActorID       string      `db:"actor_id" json:"actor_id"`
	WorkspaceID   string      `db:"workspace_id" json:"workspace_id"`
	WorkspaceType string      `db:"workspace_type" json:"workspace_type"`
	Action        string      `db:"action" json:"action"`
	ResourceType  *string     `db:"resource_type" json:"resource_type"`
	ResourceID    pgtype.UUID `db:"resource_id" json:"resource_id"`
	Details       []byte      `db:"details" json:"details"`
	IpAddress     *netip.Addr `db:"ip_address" json:"ip_address"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
	ActorName     string      `db:"actor_name" json:"actor_name"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.WorkspaceID,
			&i.WorkspaceType,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsForExport = `-- name: ListAuditLogsForExport :many
SELECT al.id, al.actor_id, al.workspace_id, al.workspace_type, al.action,
       al.resource_type, al.resource_id, al.details, al.ip_address, al.created_at,
       u.username AS actor_name
FROM audit_logs al JOIN users u ON u.id = al.actor_id
ORDER BY al.created_at DESC
`

type ListAuditLogsForExportRow struct {
	ID            string      `db:"id" json:"id"`
	ActorID       string      `db:"actor_id" json:"actor_id"`
	WorkspaceID   string      `db:"workspace_id" json:"workspace_id"`
	WorkspaceType string      `db:"workspace_type" json:"workspace_type"`
	Action        string      `db:"action" json:"action"`
	ResourceType  *string     `db:"resource_type" json:"resource_type"`
	ResourceID    pgtype.UUID `db:"resource_id" json:"resource_id"`
	Details       []byte      `db:"details" json:"details"`
	IpAddress     *netip.Addr `db:"ip_address" json:"ip_address"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
	ActorName     string      `db:"actor_name" json:"actor_name"`
}

func (q *Queries) ListAuditLogsForExport(ctx context.Context) ([]ListAuditLogsForExportRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsForExport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsForExportRow{}
	for rows.Next() {
		var i ListAuditLogsForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.WorkspaceID,
			&i.WorkspaceType,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
