// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::int FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createOAuthAccount = `-- name: CreateOAuthAccount :exec
INSERT INTO oauth_accounts (user_id, provider, provider_id)
VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

func (q *Queries) CreateOAuthAccount(ctx context.Context, userID string, provider string, providerID string) error {
	_, err := q.db.Exec(ctx, createOAuthAccount, userID, provider, providerID)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_reset_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

func (q *Queries) CreatePasswordResetToken(ctx context.Context, userID string, tokenHash string, expiresAt time.Time) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken, userID, tokenHash, expiresAt)
	return err
}

const createPersonalWorkspace = `-- name: CreatePersonalWorkspace :exec
INSERT INTO personal_workspaces (user_id, encrypted_workspace_symmetric_key)
VALUES ($1, $2)
ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) CreatePersonalWorkspace(ctx context.Context, userID string, encryptedWorkspaceSymmetricKey string) error {
	_, err := q.db.Exec(ctx, createPersonalWorkspace, userID, encryptedWorkspaceSymmetricKey)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, public_key, private_key_encrypted)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

func (q *Queries) CreateUser(ctx context.Context, username string, email string, passwordHash string, publicKey string, privateKeyEncrypted string) (string, error) {
	row := q.db.QueryRow(ctx, createUser,
		username,
		email,
		passwordHash,
		publicKey,
		privateKeyEncrypted,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createUserAdmin = `-- name: CreateUserAdmin :one
INSERT INTO users (username, email, password_hash, role, public_key, private_key_encrypted, full_name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateUserAdminParams struct {
	Username            string  `db:"username" json:"username"`
	Email               string  `db:"email" json:"email"`
	PasswordHash        string  `db:"password_hash" json:"password_hash"`
	Role                string  `db:"role" json:"role"`
	PublicKey           string  `db:"public_key" json:"public_key"`
	PrivateKeyEncrypted string  `db:"private_key_encrypted" json:"private_key_encrypted"`
	FullName            *string `db:"full_name" json:"full_name"`
}

func (q *Queries) CreateUserAdmin(ctx context.Context, arg CreateUserAdminParams) (string, error) {
	row := q.db.QueryRow(ctx, createUserAdmin,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.PublicKey,
		arg.PrivateKeyEncrypted,
		arg.FullName,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :exec
DELETE FROM sessions WHERE user_id = $1 AND token_hash != $2
`

func (q *Queries) DeleteOtherSessions(ctx context.Context, userID string, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteOtherSessions, userID, tokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const disableTOTP = `-- name: DisableTOTP :exec
UPDATE users SET totp_secret = NULL, totp_enabled = FALSE, backup_codes = NULL
WHERE id = $1
`

func (q *Queries) DisableTOTP(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, disableTOTP, id)
	return err
}

const enableTOTP = `-- name: EnableTOTP :exec
UPDATE users SET totp_secret = $1, totp_enabled = TRUE, backup_codes = $2
WHERE id = $3
`

func (q *Queries) EnableTOTP(ctx context.Context, totpSecret *string, backupCodes []string, iD string) error {
	_, err := q.db.Exec(ctx, enableTOTP, totpSecret, backupCodes, iD)
	return err
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT id, max_uses, use_count, is_active, expires_at
FROM invites WHERE code = $1
`

type GetInviteByCodeRow struct {
	ID        string             `db:"id" json:"id"`
	MaxUses   *int32             `db:"max_uses" json:"max_uses"`
	UseCount  int32              `db:"use_count" json:"use_count"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (GetInviteByCodeRow, error) {
	row := q.db.QueryRow(ctx, getInviteByCode, code)
	var i GetInviteByCodeRow
	err := row.Scan(
		&i.ID,
		&i.MaxUses,
		&i.UseCount,
		&i.IsActive,
		&i.ExpiresAt,
	)
	return i, err
}

const getOAuthAccount = `-- name: GetOAuthAccount :one
SELECT u.id, u.role, u.private_key_encrypted
FROM oauth_accounts oa JOIN users u ON u.id = oa.user_id
WHERE oa.provider = $1 AND oa.provider_id = $2
`

type GetOAuthAccountRow struct {
	ID                  string `db:"id" json:"id"`
	Role                string `db:"role" json:"role"`
	PrivateKeyEncrypted string `db:"private_key_encrypted" json:"private_key_encrypted"`
}

func (q *Queries) GetOAuthAccount(ctx context.Context, provider string, providerID string) (GetOAuthAccountRow, error) {
	row := q.db.QueryRow(ctx, getOAuthAccount, provider, providerID)
	var i GetOAuthAccountRow
	err := row.Scan(&i.ID, &i.Role, &i.PrivateKeyEncrypted)
	return i, err
}

const getOrgSetting = `-- name: GetOrgSetting :one
SELECT value FROM instance_settings WHERE key = 'organization'
`

func (q *Queries) GetOrgSetting(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getOrgSetting)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, user_id, expires_at, used
FROM password_reset_tokens WHERE token_hash = $1
`

type GetPasswordResetTokenRow struct {
	ID        string    `db:"id" json:"id"`
	UserID    string    `db:"user_id" json:"user_id"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	Used      bool      `db:"used" json:"used"`
}

func (q *Queries) GetPasswordResetToken(ctx context.Context, tokenHash string) (GetPasswordResetTokenRow, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, tokenHash)
	var i GetPasswordResetTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, public_key, private_key_encrypted,
       role, status, totp_secret, totp_enabled, backup_codes, created_at, updated_at
FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID                  string    `db:"id" json:"id"`
	Username            string    `db:"username" json:"username"`
	Email               string    `db:"email" json:"email"`
	PasswordHash        string    `db:"password_hash" json:"password_hash"`
	PublicKey           string    `db:"public_key" json:"public_key"`
	PrivateKeyEncrypted string    `db:"private_key_encrypted" json:"private_key_encrypted"`
	Role                string    `db:"role" json:"role"`
	Status              string    `db:"status" json:"status"`
	TotpSecret          *string   `db:"totp_secret" json:"totp_secret"`
	TotpEnabled         bool      `db:"totp_enabled" json:"totp_enabled"`
	BackupCodes         []string  `db:"backup_codes" json:"backup_codes"`
	CreatedAt           time.Time `db:"created_at" json:"created_at"`
	UpdatedAt           time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PublicKey,
		&i.PrivateKeyEncrypted,
		&i.Role,
		&i.Status,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.BackupCodes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, public_key, private_key_encrypted,
       role, status, totp_secret, totp_enabled, backup_codes, created_at, updated_at
FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID                  string    `db:"id" json:"id"`
	Username            string    `db:"username" json:"username"`
	Email               string    `db:"email" json:"email"`
	PublicKey           string    `db:"public_key" json:"public_key"`
	PrivateKeyEncrypted string    `db:"private_key_encrypted" json:"private_key_encrypted"`
	Role                string    `db:"role" json:"role"`
	Status              string    `db:"status" json:"status"`
	TotpSecret          *string   `db:"totp_secret" json:"totp_secret"`
	TotpEnabled         bool      `db:"totp_enabled" json:"totp_enabled"`
	BackupCodes         []string  `db:"backup_codes" json:"backup_codes"`
	CreatedAt           time.Time `db:"created_at" json:"created_at"`
	UpdatedAt           time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PublicKey,
		&i.PrivateKeyEncrypted,
		&i.Role,
		&i.Status,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.BackupCodes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT id, username, email, password_hash, private_key_encrypted,
       role, status, totp_enabled
FROM users WHERE email = $1
`

type GetUserForLoginRow struct {
	ID                  string `db:"id" json:"id"`
	Username            string `db:"username" json:"username"`
	Email               string `db:"email" json:"email"`
	PasswordHash        string `db:"password_hash" json:"password_hash"`
	PrivateKeyEncrypted string `db:"private_key_encrypted" json:"private_key_encrypted"`
	Role                string `db:"role" json:"role"`
	Status              string `db:"status" json:"status"`
	TotpEnabled         bool   `db:"totp_enabled" json:"totp_enabled"`
}

func (q *Queries) GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, email)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PrivateKeyEncrypted,
		&i.Role,
		&i.Status,
		&i.TotpEnabled,
	)
	return i, err
}

const getUserForLoginByUsername = `-- name: GetUserForLoginByUsername :one
SELECT id, username, email, password_hash, public_key, private_key_encrypted,
       role, status, totp_enabled
FROM users WHERE username = $1
`

type GetUserForLoginByUsernameRow struct {
	ID                  string `db:"id" json:"id"`
	Username            string `db:"username" json:"username"`
	Email               string `db:"email" json:"email"`
	PasswordHash        string `db:"password_hash" json:"password_hash"`
	PublicKey           string `db:"public_key" json:"public_key"`
	PrivateKeyEncrypted string `db:"private_key_encrypted" json:"private_key_encrypted"`
	Role                string `db:"role" json:"role"`
	Status              string `db:"status" json:"status"`
	TotpEnabled         bool   `db:"totp_enabled" json:"totp_enabled"`
}

func (q *Queries) GetUserForLoginByUsername(ctx context.Context, username string) (GetUserForLoginByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserForLoginByUsername, username)
	var i GetUserForLoginByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PublicKey,
		&i.PrivateKeyEncrypted,
		&i.Role,
		&i.Status,
		&i.TotpEnabled,
	)
	return i, err
}

const getUserPasswordHash = `-- name: GetUserPasswordHash :one
SELECT password_hash FROM users WHERE id = $1
`

func (q *Queries) GetUserPasswordHash(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getUserPasswordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getUserPrivateKeyInfo = `-- name: GetUserPrivateKeyInfo :one
SELECT public_key, private_key_encrypted, totp_enabled FROM users WHERE id = $1
`

type GetUserPrivateKeyInfoRow struct {
	PublicKey           string `db:"public_key" json:"public_key"`
	PrivateKeyEncrypted string `db:"private_key_encrypted" json:"private_key_encrypted"`
	TotpEnabled         bool   `db:"totp_enabled" json:"totp_enabled"`
}

func (q *Queries) GetUserPrivateKeyInfo(ctx context.Context, id string) (GetUserPrivateKeyInfoRow, error) {
	row := q.db.QueryRow(ctx, getUserPrivateKeyInfo, id)
	var i GetUserPrivateKeyInfoRow
	err := row.Scan(&i.PublicKey, &i.PrivateKeyEncrypted, &i.TotpEnabled)
	return i, err
}

const getUserPublicKeyByEmail = `-- name: GetUserPublicKeyByEmail :one
SELECT id, public_key FROM users WHERE email = $1
`

type GetUserPublicKeyByEmailRow struct {
	ID        string `db:"id" json:"id"`
	PublicKey string `db:"public_key" json:"public_key"`
}

func (q *Queries) GetUserPublicKeyByEmail(ctx context.Context, email string) (GetUserPublicKeyByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserPublicKeyByEmail, email)
	var i GetUserPublicKeyByEmailRow
	err := row.Scan(&i.ID, &i.PublicKey)
	return i, err
}

const getUserPublicKeyByUsername = `-- name: GetUserPublicKeyByUsername :one
SELECT id, public_key FROM users WHERE username = $1
`

type GetUserPublicKeyByUsernameRow struct {
	ID        string `db:"id" json:"id"`
	PublicKey string `db:"public_key" json:"public_key"`
}

func (q *Queries) GetUserPublicKeyByUsername(ctx context.Context, username string) (GetUserPublicKeyByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserPublicKeyByUsername, username)
	var i GetUserPublicKeyByUsernameRow
	err := row.Scan(&i.ID, &i.PublicKey)
	return i, err
}

const getUserTOTPSecret = `-- name: GetUserTOTPSecret :one
SELECT totp_secret FROM users WHERE id = $1
`

func (q *Queries) GetUserTOTPSecret(ctx context.Context, id string) (*string, error) {
	row := q.db.QueryRow(ctx, getUserTOTPSecret, id)
	var totp_secret *string
	err := row.Scan(&totp_secret)
	return totp_secret, err
}

const incrementInviteUseCount = `-- name: IncrementInviteUseCount :exec
UPDATE invites SET use_count = use_count + 1 WHERE id = $1
`

func (q *Queries) IncrementInviteUseCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementInviteUseCount, id)
	return err
}

const markResetTokenUsed = `-- name: MarkResetTokenUsed :exec
UPDATE password_reset_tokens SET used = TRUE WHERE id = $1
`

func (q *Queries) MarkResetTokenUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markResetTokenUsed, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $1 WHERE id = $2
`

func (q *Queries) UpdateUserPassword(ctx context.Context, passwordHash string, iD string) error {
	_, err := q.db.Exec(ctx, updateUserPassword, passwordHash, iD)
	return err
}

const upsertOAuthUser = `-- name: UpsertOAuthUser :one
INSERT INTO users (username, email, password_hash, public_key, private_key_encrypted)
VALUES ($1, $2, 'oauth-no-password', '', '')
ON CONFLICT (email) DO UPDATE SET username = EXCLUDED.username
RETURNING id
`

func (q *Queries) UpsertOAuthUser(ctx context.Context, username string, email string) (string, error) {
	row := q.db.QueryRow(ctx, upsertOAuthUser, username, email)
	var id string
	err := row.Scan(&id)
	return id, err
}
