// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: envs.sql

package repository

import (
	"context"
)

const createEnv = `-- name: CreateEnv :one
INSERT INTO environments (app_id, name) VALUES ($1, $2) RETURNING id, app_id, name, created_at, updated_at
`

func (q *Queries) CreateEnv(ctx context.Context, appID string, name string) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnv, appID, name)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnv = `-- name: DeleteEnv :exec
DELETE FROM environments WHERE id = $1
`

func (q *Queries) DeleteEnv(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteEnv, id)
	return err
}

const getEnvByAppAndName = `-- name: GetEnvByAppAndName :one
SELECT id, app_id, name, created_at, updated_at FROM environments WHERE app_id = $1 AND name = $2
`

func (q *Queries) GetEnvByAppAndName(ctx context.Context, appID string, name string) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvByAppAndName, appID, name)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvByID = `-- name: GetEnvByID :one
SELECT id, app_id, name, created_at, updated_at FROM environments WHERE id = $1
`

func (q *Queries) GetEnvByID(ctx context.Context, id string) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvByID, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvs = `-- name: ListEnvs :many
SELECT id, app_id, name, created_at, updated_at FROM environments WHERE app_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListEnvs(ctx context.Context, appID string) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvs, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnv = `-- name: UpdateEnv :exec
UPDATE environments SET name = $1, updated_at = NOW() WHERE id = $2
`

func (q *Queries) UpdateEnv(ctx context.Context, name string, iD string) error {
	_, err := q.db.Exec(ctx, updateEnv, name, iD)
	return err
}
