// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: middleware_auth.sql

package repository

import (
	"context"
	"time"
)

const getSessionForAuth = `-- name: GetSessionForAuth :one
SELECT u.id, u.username, u.email, u.role, u.status, s.expires_at, s.client
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
`

type GetSessionForAuthRow struct {
	ID        string    `db:"id" json:"id"`
	Username  string    `db:"username" json:"username"`
	Email     string    `db:"email" json:"email"`
	Role      string    `db:"role" json:"role"`
	Status    string    `db:"status" json:"status"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	Client    string    `db:"client" json:"client"`
}

func (q *Queries) GetSessionForAuth(ctx context.Context, tokenHash string) (GetSessionForAuthRow, error) {
	row := q.db.QueryRow(ctx, getSessionForAuth, tokenHash)
	var i GetSessionForAuthRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.ExpiresAt,
		&i.Client,
	)
	return i, err
}

const getUserFromAPIKey = `-- name: GetUserFromAPIKey :one
SELECT u.id, u.username, u.email, u.role, u.status
FROM api_keys ak JOIN users u ON u.id = ak.user_id
WHERE ak.key_hash = $1
`

type GetUserFromAPIKeyRow struct {
	ID       string `db:"id" json:"id"`
	Username string `db:"username" json:"username"`
	Email    string `db:"email" json:"email"`
	Role     string `db:"role" json:"role"`
	Status   string `db:"status" json:"status"`
}

func (q *Queries) GetUserFromAPIKey(ctx context.Context, keyHash string) (GetUserFromAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getUserFromAPIKey, keyHash)
	var i GetUserFromAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Status,
	)
	return i, err
}
