// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        string             `db:"id" json:"id"`
	UserID    string             `db:"user_id" json:"user_id"`
	Name      string             `db:"name" json:"name"`
	KeyHash   string             `db:"key_hash" json:"key_hash"`
	KeyPrefix string             `db:"key_prefix" json:"key_prefix"`
	LastUsed  pgtype.Timestamptz `db:"last_used" json:"last_used"`
	CreatedAt time.Time          `db:"created_at" json:"created_at"`
}

type App struct {
	ID            string    `db:"id" json:"id"`
	Name          string    `db:"name" json:"name"`
	Description   *string   `db:"description" json:"description"`
	WorkspaceID   string    `db:"workspace_id" json:"workspace_id"`
	WorkspaceType string    `db:"workspace_type" json:"workspace_type"`
	CreatedBy     string    `db:"created_by" json:"created_by"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time `db:"updated_at" json:"updated_at"`
}

type AuditLog struct {
	ID            string      `db:"id" json:"id"`
	ActorID       string      `db:"actor_id" json:"actor_id"`
	WorkspaceID   string      `db:"workspace_id" json:"workspace_id"`
	WorkspaceType string      `db:"workspace_type" json:"workspace_type"`
	Action        string      `db:"action" json:"action"`
	ResourceType  *string     `db:"resource_type" json:"resource_type"`
	ResourceID    pgtype.UUID `db:"resource_id" json:"resource_id"`
	Details       []byte      `db:"details" json:"details"`
	IpAddress     *netip.Addr `db:"ip_address" json:"ip_address"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
}

type Environment struct {
	ID        string    `db:"id" json:"id"`
	AppID     string    `db:"app_id" json:"app_id"`
	Name      string    `db:"name" json:"name"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type InstanceSetting struct {
	Key       string    `db:"key" json:"key"`
	Value     []byte    `db:"value" json:"value"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type Invite struct {
	ID        string             `db:"id" json:"id"`
	Code      string             `db:"code" json:"code"`
	MaxUses   *int32             `db:"max_uses" json:"max_uses"`
	UseCount  int32              `db:"use_count" json:"use_count"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedBy string             `db:"created_by" json:"created_by"`
	CreatedAt time.Time          `db:"created_at" json:"created_at"`
}

type OauthAccount struct {
	ID         string    `db:"id" json:"id"`
	UserID     string    `db:"user_id" json:"user_id"`
	Provider   string    `db:"provider" json:"provider"`
	ProviderID string    `db:"provider_id" json:"provider_id"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

type PasswordResetToken struct {
	ID        string    `db:"id" json:"id"`
	UserID    string    `db:"user_id" json:"user_id"`
	TokenHash string    `db:"token_hash" json:"token_hash"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	Used      bool      `db:"used" json:"used"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type PersonalWorkspace struct {
	ID                             string    `db:"id" json:"id"`
	UserID                         string    `db:"user_id" json:"user_id"`
	EncryptedWorkspaceSymmetricKey string    `db:"encrypted_workspace_symmetric_key" json:"encrypted_workspace_symmetric_key"`
	CreatedAt                      time.Time `db:"created_at" json:"created_at"`
}

type Secret struct {
	ID             string    `db:"id" json:"id"`
	EnvironmentID  string    `db:"environment_id" json:"environment_id"`
	Key            string    `db:"key" json:"key"`
	EncryptedValue string    `db:"encrypted_value" json:"encrypted_value"`
	CreatedBy      string    `db:"created_by" json:"created_by"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}

type SecretHistory struct {
	ID                string      `db:"id" json:"id"`
	SecretID          pgtype.UUID `db:"secret_id" json:"secret_id"`
	OldEncryptedValue *string     `db:"old_encrypted_value" json:"old_encrypted_value"`
	NewEncryptedValue *string     `db:"new_encrypted_value" json:"new_encrypted_value"`
	ChangedBy         string      `db:"changed_by" json:"changed_by"`
	Action            string      `db:"action" json:"action"`
	CreatedAt         time.Time   `db:"created_at" json:"created_at"`
}

type Session struct {
	ID         string    `db:"id" json:"id"`
	UserID     string    `db:"user_id" json:"user_id"`
	TokenHash  string    `db:"token_hash" json:"token_hash"`
	DeviceInfo *string   `db:"device_info" json:"device_info"`
	IpAddress  *string   `db:"ip_address" json:"ip_address"`
	ExpiresAt  time.Time `db:"expires_at" json:"expires_at"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	LastUsedAt time.Time `db:"last_used_at" json:"last_used_at"`
	Client     string    `db:"client" json:"client"`
}

type Team struct {
	ID        string    `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	OwnerID   string    `db:"owner_id" json:"owner_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type TeamMember struct {
	ID                        string    `db:"id" json:"id"`
	TeamID                    string    `db:"team_id" json:"team_id"`
	UserID                    string    `db:"user_id" json:"user_id"`
	Role                      string    `db:"role" json:"role"`
	EncryptedTeamSymmetricKey string    `db:"encrypted_team_symmetric_key" json:"encrypted_team_symmetric_key"`
	CreatedAt                 time.Time `db:"created_at" json:"created_at"`
	UpdatedAt                 time.Time `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID                  string    `db:"id" json:"id"`
	Username            string    `db:"username" json:"username"`
	Email               string    `db:"email" json:"email"`
	PasswordHash        string    `db:"password_hash" json:"password_hash"`
	PublicKey           string    `db:"public_key" json:"public_key"`
	PrivateKeyEncrypted string    `db:"private_key_encrypted" json:"private_key_encrypted"`
	CreatedAt           time.Time `db:"created_at" json:"created_at"`
	UpdatedAt           time.Time `db:"updated_at" json:"updated_at"`
	Role                string    `db:"role" json:"role"`
	Status              string    `db:"status" json:"status"`
	TotpSecret          *string   `db:"totp_secret" json:"totp_secret"`
	TotpEnabled         bool      `db:"totp_enabled" json:"totp_enabled"`
	BackupCodes         []string  `db:"backup_codes" json:"backup_codes"`
}

type WebhookDelivery struct {
	ID         string    `db:"id" json:"id"`
	Event      string    `db:"event" json:"event"`
	Payload    []byte    `db:"payload" json:"payload"`
	StatusCode *int32    `db:"status_code" json:"status_code"`
	Success    bool      `db:"success" json:"success"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}
