// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddTeamMember(ctx context.Context, teamID string, userID string, role string, encryptedTeamSymmetricKey string) error
	AdminUpdateUser(ctx context.Context, column1 interface{}, column2 interface{}, column3 interface{}, column4 interface{}, iD string) error
	CountAuditLogs(ctx context.Context, column1 string, column2 string, column3 time.Time, column4 time.Time) (int64, error)
	CountPersonalSecrets(ctx context.Context) (int64, error)
	CountSecretAccessesSince(ctx context.Context, createdAt time.Time) (int64, error)
	CountSecretsTotal(ctx context.Context) (int64, error)
	CountTeamsTotal(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int32, error)
	CountUsersAdmin(ctx context.Context, dollar_1 string) (int64, error)
	CountUsersTotal(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, userID string, name string, keyHash string, keyPrefix string) (CreateAPIKeyRow, error)
	CreateApp(ctx context.Context, name string, description *string, workspaceID string, workspaceType string, createdBy string) (App, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateEnv(ctx context.Context, appID string, name string) (Environment, error)
	CreateInvite(ctx context.Context, code string, maxUses *int32, expiresAt pgtype.Timestamptz, createdBy string) (CreateInviteRow, error)
	CreateOAuthAccount(ctx context.Context, userID string, provider string, providerID string) error
	CreatePasswordResetToken(ctx context.Context, userID string, tokenHash string, expiresAt time.Time) error
	CreatePersonalWorkspace(ctx context.Context, userID string, encryptedWorkspaceSymmetricKey string) error
	CreateSecret(ctx context.Context, environmentID string, key string, encryptedValue string, createdBy string) (Secret, error)
	CreateSecretHistoryEntry(ctx context.Context, secretID pgtype.UUID, oldEncryptedValue *string, newEncryptedValue *string, changedBy string, action string) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateTeam(ctx context.Context, name string, ownerID string) (Team, error)
	CreateUser(ctx context.Context, username string, email string, passwordHash string, publicKey string, privateKeyEncrypted string) (string, error)
	CreateUserAdmin(ctx context.Context, arg CreateUserAdminParams) (string, error)
	DailyActivity(ctx context.Context, dollar_1 pgtype.Date) ([]DailyActivityRow, error)
	DeactivateInvite(ctx context.Context, id string) (int64, error)
	DeleteAPIKey(ctx context.Context, iD string, userID string) (int64, error)
	DeleteApp(ctx context.Context, id string) error
	DeleteEnv(ctx context.Context, id string) error
	DeleteInvite(ctx context.Context, id string) (int64, error)
	DeleteOtherSessions(ctx context.Context, userID string, tokenHash string) error
	DeleteSecret(ctx context.Context, id string) error
	DeleteSessionByHash(ctx context.Context, tokenHash string) error
	DeleteSessionByID(ctx context.Context, iD string, userID string) (int64, error)
	DeleteTeam(ctx context.Context, id string) error
	DeleteUserByID(ctx context.Context, id string) error
	DeleteUserSessions(ctx context.Context, userID string) error
	DisableTOTP(ctx context.Context, id string) error
	EnableTOTP(ctx context.Context, totpSecret *string, backupCodes []string, iD string) error
	GetAppByID(ctx context.Context, id string) (App, error)
	GetEncryptedTeamKey(ctx context.Context, teamID string, userID string) (string, error)
	GetEnvByAppAndName(ctx context.Context, appID string, name string) (Environment, error)
	GetEnvByID(ctx context.Context, id string) (Environment, error)
	GetInstanceSetting(ctx context.Context, key string) ([]byte, error)
	GetInviteByCode(ctx context.Context, code string) (GetInviteByCodeRow, error)
	GetOAuthAccount(ctx context.Context, provider string, providerID string) (GetOAuthAccountRow, error)
	GetOrgSetting(ctx context.Context) ([]byte, error)
	GetPasswordResetToken(ctx context.Context, tokenHash string) (GetPasswordResetTokenRow, error)
	GetPersonalWorkspaceByUser(ctx context.Context, userID string) (GetPersonalWorkspaceByUserRow, error)
	GetPersonalWorkspaceID(ctx context.Context, userID string) (string, error)
	GetSecretByID(ctx context.Context, iD string, environmentID string) (GetSecretByIDRow, error)
	GetSecretByKey(ctx context.Context, environmentID string, key string) (Secret, error)
	GetSecretHistory(ctx context.Context, secretID pgtype.UUID) ([]GetSecretHistoryRow, error)
	GetSessionForAuth(ctx context.Context, tokenHash string) (GetSessionForAuthRow, error)
	GetSessionWithUser(ctx context.Context, tokenHash string) (GetSessionWithUserRow, error)
	GetTeamByID(ctx context.Context, id string) (Team, error)
	GetTeamMember(ctx context.Context, teamID string, userID string) (TeamMember, error)
	GetTeamOwner(ctx context.Context, id string) (string, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error)
	GetUserForLoginByUsername(ctx context.Context, username string) (GetUserForLoginByUsernameRow, error)
	GetUserFromAPIKey(ctx context.Context, keyHash string) (GetUserFromAPIKeyRow, error)
	GetUserPasswordHash(ctx context.Context, id string) (string, error)
	GetUserPrivateKeyInfo(ctx context.Context, id string) (GetUserPrivateKeyInfoRow, error)
	GetUserPublicKeyByEmail(ctx context.Context, email string) (GetUserPublicKeyByEmailRow, error)
	GetUserTOTPSecret(ctx context.Context, id string) (*string, error)
	IncrementInviteUseCount(ctx context.Context, id string) error
	ListAPIKeys(ctx context.Context, userID string) ([]ListAPIKeysRow, error)
	ListActiveSessions(ctx context.Context, userID string) ([]ListActiveSessionsRow, error)
	ListAppsForWorkspace(ctx context.Context, workspaceID string, workspaceType string) ([]App, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	ListAuditLogsForExport(ctx context.Context) ([]ListAuditLogsForExportRow, error)
	ListEnvs(ctx context.Context, appID string) ([]Environment, error)
	ListInvites(ctx context.Context) ([]ListInvitesRow, error)
	ListPersonalApps(ctx context.Context, userID string) ([]App, error)
	ListSecrets(ctx context.Context, environmentID string) ([]ListSecretsRow, error)
	ListSecretsForExport(ctx context.Context, environmentID string) ([]ListSecretsForExportRow, error)
	ListTeamApps(ctx context.Context, userID string) ([]App, error)
	ListTeamMembers(ctx context.Context, teamID string) ([]ListTeamMembersRow, error)
	ListTeamsByMember(ctx context.Context, userID string) ([]Team, error)
	ListTeamsByOwner(ctx context.Context, ownerID string) ([]Team, error)
	ListUsersAdmin(ctx context.Context, column1 string, limit int32, offset int32) ([]ListUsersAdminRow, error)
	MarkResetTokenUsed(ctx context.Context, id string) error
	RemoveTeamMember(ctx context.Context, teamID string, userID string) error
	TopTeamsBySecretCount(ctx context.Context) ([]TopTeamsBySecretCountRow, error)
	TopUsersByEventCount(ctx context.Context, createdAt time.Time) ([]TopUsersByEventCountRow, error)
	UpdateAPIKeyLastUsed(ctx context.Context, keyHash string) error
	UpdateApp(ctx context.Context, name string, description *string, iD string) error
	UpdateEnv(ctx context.Context, name string, iD string) error
	UpdateSecret(ctx context.Context, encryptedValue string, iD string) (Secret, error)
	UpdateSessionLastUsed(ctx context.Context, tokenHash string) error
	UpdateTeam(ctx context.Context, name string, iD string) error
	UpdateTeamMemberRole(ctx context.Context, role string, teamID string, userID string) error
	UpdateUserPassword(ctx context.Context, passwordHash string, iD string) error
	UpdateUserProfile(ctx context.Context, column1 interface{}, column2 interface{}, iD string) error
	UpsertInstanceSetting(ctx context.Context, key string, value []byte) error
	UpsertOAuthUser(ctx context.Context, username string, email string) (string, error)
	UpsertSecret(ctx context.Context, environmentID string, key string, encryptedValue string, createdBy string) (Secret, error)
}

var _ Querier = (*Queries)(nil)
