// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSecret = `-- name: CreateSecret :one
INSERT INTO secrets (environment_id, key, encrypted_value, created_by)
VALUES ($1, $2, $3, $4) RETURNING id, environment_id, key, encrypted_value, created_by, created_at, updated_at
`

func (q *Queries) CreateSecret(ctx context.Context, environmentID string, key string, encryptedValue string, createdBy string) (Secret, error) {
	row := q.db.QueryRow(ctx, createSecret,
		environmentID,
		key,
		encryptedValue,
		createdBy,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Key,
		&i.EncryptedValue,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSecretHistoryEntry = `-- name: CreateSecretHistoryEntry :exec
INSERT INTO secret_history (secret_id, old_encrypted_value, new_encrypted_value, changed_by, action)
VALUES ($1, $2, $3, $4, $5)
`

func (q *Queries) CreateSecretHistoryEntry(ctx context.Context, secretID pgtype.UUID, oldEncryptedValue *string, newEncryptedValue *string, changedBy string, action string) error {
	_, err := q.db.Exec(ctx, createSecretHistoryEntry,
		secretID,
		oldEncryptedValue,
		newEncryptedValue,
		changedBy,
		action,
	)
	return err
}

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM secrets WHERE id = $1
`

func (q *Queries) DeleteSecret(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSecret, id)
	return err
}

const getSecretByID = `-- name: GetSecretByID :one
SELECT s.id, s.environment_id, s.key, s.encrypted_value, s.created_by,
       s.created_at, s.updated_at, u.username AS created_by_name
FROM secrets s JOIN users u ON u.id = s.created_by
WHERE s.id = $1 AND s.environment_id = $2
`

type GetSecretByIDRow struct {
	ID             string    `db:"id" json:"id"`
	EnvironmentID  string    `db:"environment_id" json:"environment_id"`
	Key            string    `db:"key" json:"key"`
	EncryptedValue string    `db:"encrypted_value" json:"encrypted_value"`
	CreatedBy      string    `db:"created_by" json:"created_by"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
	CreatedByName  string    `db:"created_by_name" json:"created_by_name"`
}

func (q *Queries) GetSecretByID(ctx context.Context, iD string, environmentID string) (GetSecretByIDRow, error) {
	row := q.db.QueryRow(ctx, getSecretByID, iD, environmentID)
	var i GetSecretByIDRow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Key,
		&i.EncryptedValue,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByName,
	)
	return i, err
}

const getSecretByKey = `-- name: GetSecretByKey :one
SELECT id, environment_id, key, encrypted_value, created_by, created_at, updated_at FROM secrets WHERE environment_id = $1 AND key = $2
`

func (q *Queries) GetSecretByKey(ctx context.Context, environmentID string, key string) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecretByKey, environmentID, key)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Key,
		&i.EncryptedValue,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecretHistory = `-- name: GetSecretHistory :many
SELECT sh.id, sh.secret_id, sh.old_encrypted_value, sh.new_encrypted_value,
       sh.action, sh.created_at, u.username AS changed_by_name
FROM secret_history sh JOIN users u ON u.id = sh.changed_by
WHERE sh.secret_id = $1
ORDER BY sh.created_at DESC
`

type GetSecretHistoryRow struct {
	ID                string      `db:"id" json:"id"`
	SecretID          pgtype.UUID `db:"secret_id" json:"secret_id"`
	OldEncryptedValue *string     `db:"old_encrypted_value" json:"old_encrypted_value"`
	NewEncryptedValue *string     `db:"new_encrypted_value" json:"new_encrypted_value"`
	Action            string      `db:"action" json:"action"`
	CreatedAt         time.Time   `db:"created_at" json:"created_at"`
	ChangedByName     string      `db:"changed_by_name" json:"changed_by_name"`
}

func (q *Queries) GetSecretHistory(ctx context.Context, secretID pgtype.UUID) ([]GetSecretHistoryRow, error) {
	rows, err := q.db.Query(ctx, getSecretHistory, secretID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSecretHistoryRow{}
	for rows.Next() {
		var i GetSecretHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.SecretID,
			&i.OldEncryptedValue,
			&i.NewEncryptedValue,
			&i.Action,
			&i.CreatedAt,
			&i.ChangedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecrets = `-- name: ListSecrets :many
SELECT s.id, s.environment_id, s.key, s.encrypted_value, s.created_by,
       s.created_at, s.updated_at, u.username AS created_by_name
FROM secrets s JOIN users u ON u.id = s.created_by
WHERE s.environment_id = $1
ORDER BY s.created_at DESC
`

type ListSecretsRow struct {
	ID             string    `db:"id" json:"id"`
	EnvironmentID  string    `db:"environment_id" json:"environment_id"`
	Key            string    `db:"key" json:"key"`
	EncryptedValue string    `db:"encrypted_value" json:"encrypted_value"`
	CreatedBy      string    `db:"created_by" json:"created_by"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
	CreatedByName  string    `db:"created_by_name" json:"created_by_name"`
}

func (q *Queries) ListSecrets(ctx context.Context, environmentID string) ([]ListSecretsRow, error) {
	rows, err := q.db.Query(ctx, listSecrets, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretsRow{}
	for rows.Next() {
		var i ListSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Key,
			&i.EncryptedValue,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretsForExport = `-- name: ListSecretsForExport :many
SELECT key, encrypted_value FROM secrets WHERE environment_id = $1
`

type ListSecretsForExportRow struct {
	Key            string `db:"key" json:"key"`
	EncryptedValue string `db:"encrypted_value" json:"encrypted_value"`
}

func (q *Queries) ListSecretsForExport(ctx context.Context, environmentID string) ([]ListSecretsForExportRow, error) {
	rows, err := q.db.Query(ctx, listSecretsForExport, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretsForExportRow{}
	for rows.Next() {
		var i ListSecretsForExportRow
		if err := rows.Scan(&i.Key, &i.EncryptedValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecret = `-- name: UpdateSecret :one
UPDATE secrets SET encrypted_value = $1, updated_at = NOW()
WHERE id = $2 RETURNING id, environment_id, key, encrypted_value, created_by, created_at, updated_at
`

func (q *Queries) UpdateSecret(ctx context.Context, encryptedValue string, iD string) (Secret, error) {
	row := q.db.QueryRow(ctx, updateSecret, encryptedValue, iD)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Key,
		&i.EncryptedValue,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSecret = `-- name: UpsertSecret :one
INSERT INTO secrets (environment_id, key, encrypted_value, created_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (environment_id, key)
DO UPDATE SET encrypted_value = EXCLUDED.encrypted_value, updated_at = NOW()
RETURNING id, environment_id, key, encrypted_value, created_by, created_at, updated_at
`

func (q *Queries) UpsertSecret(ctx context.Context, environmentID string, key string, encryptedValue string, createdBy string) (Secret, error) {
	row := q.db.QueryRow(ctx, upsertSecret,
		environmentID,
		key,
		encryptedValue,
		createdBy,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Key,
		&i.EncryptedValue,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
