// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package repository

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (user_id, token_hash, device_info, ip_address, expires_at, client)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSessionParams struct {
	UserID     string    `db:"user_id" json:"user_id"`
	TokenHash  string    `db:"token_hash" json:"token_hash"`
	DeviceInfo *string   `db:"device_info" json:"device_info"`
	IpAddress  *string   `db:"ip_address" json:"ip_address"`
	ExpiresAt  time.Time `db:"expires_at" json:"expires_at"`
	Client     string    `db:"client" json:"client"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.DeviceInfo,
		arg.IpAddress,
		arg.ExpiresAt,
		arg.Client,
	)
	return err
}

const deleteSessionByHash = `-- name: DeleteSessionByHash :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByHash, tokenHash)
	return err
}

const deleteSessionByID = `-- name: DeleteSessionByID :execrows
DELETE FROM sessions WHERE id = $1 AND user_id = $2
`

func (q *Queries) DeleteSessionByID(ctx context.Context, iD string, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionByID, iD, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT u.id, u.username, u.email, u.role, u.status, s.expires_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
`

type GetSessionWithUserRow struct {
	ID        string    `db:"id" json:"id"`
	Username  string    `db:"username" json:"username"`
	Email     string    `db:"email" json:"email"`
	Role      string    `db:"role" json:"role"`
	Status    string    `db:"status" json:"status"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
}

func (q *Queries) GetSessionWithUser(ctx context.Context, tokenHash string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUser, tokenHash)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT id, device_info, ip_address, expires_at, created_at, last_used_at, client
FROM sessions
WHERE user_id = $1 AND expires_at > NOW()
ORDER BY last_used_at DESC
`

type ListActiveSessionsRow struct {
	ID         string    `db:"id" json:"id"`
	DeviceInfo *string   `db:"device_info" json:"device_info"`
	IpAddress  *string   `db:"ip_address" json:"ip_address"`
	ExpiresAt  time.Time `db:"expires_at" json:"expires_at"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	LastUsedAt time.Time `db:"last_used_at" json:"last_used_at"`
	Client     string    `db:"client" json:"client"`
}

func (q *Queries) ListActiveSessions(ctx context.Context, userID string) ([]ListActiveSessionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSessionsRow{}
	for rows.Next() {
		var i ListActiveSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceInfo,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.Client,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionLastUsed = `-- name: UpdateSessionLastUsed :exec
UPDATE sessions SET last_used_at = NOW() WHERE token_hash = $1
`

func (q *Queries) UpdateSessionLastUsed(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, updateSessionLastUsed, tokenHash)
	return err
}
