// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package repository

import (
	"context"
	"time"
)

const addTeamMember = `-- name: AddTeamMember :exec
INSERT INTO team_members (team_id, user_id, role, encrypted_team_symmetric_key)
VALUES ($1, $2, $3, $4)
`

func (q *Queries) AddTeamMember(ctx context.Context, teamID string, userID string, role string, encryptedTeamSymmetricKey string) error {
	_, err := q.db.Exec(ctx, addTeamMember,
		teamID,
		userID,
		role,
		encryptedTeamSymmetricKey,
	)
	return err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, owner_id) VALUES ($1, $2) RETURNING id, name, owner_id, created_at, updated_at
`

func (q *Queries) CreateTeam(ctx context.Context, name string, ownerID string) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, name, ownerID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const getEncryptedTeamKey = `-- name: GetEncryptedTeamKey :one
SELECT encrypted_team_symmetric_key FROM team_members
WHERE team_id = $1 AND user_id = $2
`

func (q *Queries) GetEncryptedTeamKey(ctx context.Context, teamID string, userID string) (string, error) {
	row := q.db.QueryRow(ctx, getEncryptedTeamKey, teamID, userID)
	var encrypted_team_symmetric_key string
	err := row.Scan(&encrypted_team_symmetric_key)
	return encrypted_team_symmetric_key, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, owner_id, created_at, updated_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMember = `-- name: GetTeamMember :one
SELECT id, team_id, user_id, role, encrypted_team_symmetric_key, created_at, updated_at FROM team_members WHERE team_id = $1 AND user_id = $2
`

func (q *Queries) GetTeamMember(ctx context.Context, teamID string, userID string) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMember, teamID, userID)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.EncryptedTeamSymmetricKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamOwner = `-- name: GetTeamOwner :one
SELECT owner_id FROM teams WHERE id = $1
`

func (q *Queries) GetTeamOwner(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getTeamOwner, id)
	var owner_id string
	err := row.Scan(&owner_id)
	return owner_id, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT u.id, u.username, u.email, tm.role, tm.encrypted_team_symmetric_key, tm.created_at
FROM team_members tm JOIN users u ON u.id = tm.user_id
WHERE tm.team_id = $1
`

type ListTeamMembersRow struct {
	ID                        string    `db:"id" json:"id"`
	Username                  string    `db:"username" json:"username"`
	Email                     string    `db:"email" json:"email"`
	Role                      string    `db:"role" json:"role"`
	EncryptedTeamSymmetricKey string    `db:"encrypted_team_symmetric_key" json:"encrypted_team_symmetric_key"`
	CreatedAt                 time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID string) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Role,
			&i.EncryptedTeamSymmetricKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByMember = `-- name: ListTeamsByMember :many
SELECT t.id, t.name, t.owner_id, t.created_at, t.updated_at FROM teams t
JOIN team_members tm ON tm.team_id = t.id
WHERE tm.user_id = $1
ORDER BY t.created_at DESC
`

func (q *Queries) ListTeamsByMember(ctx context.Context, userID string) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByMember, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByOwner = `-- name: ListTeamsByOwner :many
SELECT id, name, owner_id, created_at, updated_at FROM teams WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTeamsByOwner(ctx context.Context, ownerID string) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2
`

func (q *Queries) RemoveTeamMember(ctx context.Context, teamID string, userID string) error {
	_, err := q.db.Exec(ctx, removeTeamMember, teamID, userID)
	return err
}

const updateTeam = `-- name: UpdateTeam :exec
UPDATE teams SET name = $1, updated_at = NOW() WHERE id = $2
`

func (q *Queries) UpdateTeam(ctx context.Context, name string, iD string) error {
	_, err := q.db.Exec(ctx, updateTeam, name, iD)
	return err
}

const updateTeamMemberRole = `-- name: UpdateTeamMemberRole :exec
UPDATE team_members SET role = $1, updated_at = NOW()
WHERE team_id = $2 AND user_id = $3
`

func (q *Queries) UpdateTeamMemberRole(ctx context.Context, role string, teamID string, userID string) error {
	_, err := q.db.Exec(ctx, updateTeamMemberRole, role, teamID, userID)
	return err
}
