// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"
	"time"
)

const adminUpdateUser = `-- name: AdminUpdateUser :exec
UPDATE users SET
    username   = CASE WHEN $1 != '' THEN $1 ELSE username END,
    email      = CASE WHEN $2 != '' THEN $2 ELSE email END,
    role       = CASE WHEN $3 != '' THEN $3 ELSE role END,
    status     = CASE WHEN $4 != '' THEN $4 ELSE status END,
    updated_at = NOW()
WHERE id = $5
`

func (q *Queries) AdminUpdateUser(ctx context.Context, column1 interface{}, column2 interface{}, column3 interface{}, column4 interface{}, iD string) error {
	_, err := q.db.Exec(ctx, adminUpdateUser,
		column1,
		column2,
		column3,
		column4,
		iD,
	)
	return err
}

const countUsersAdmin = `-- name: CountUsersAdmin :one
SELECT COUNT(*) FROM users
WHERE ($1::text = '' OR LOWER(username) LIKE $1 OR LOWER(email) LIKE $1)
`

func (q *Queries) CountUsersAdmin(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersAdmin, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersTotal = `-- name: CountUsersTotal :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsersTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersTotal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUserByID, id)
	return err
}

const listUsersAdmin = `-- name: ListUsersAdmin :many
SELECT id, username, email, role, status, created_at
FROM users
WHERE ($1::text = '' OR LOWER(username) LIKE $1 OR LOWER(email) LIKE $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersAdminRow struct {
	ID        string    `db:"id" json:"id"`
	Username  string    `db:"username" json:"username"`
	Email     string    `db:"email" json:"email"`
	Role      string    `db:"role" json:"role"`
	Status    string    `db:"status" json:"status"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) ListUsersAdmin(ctx context.Context, column1 string, limit int32, offset int32) ([]ListUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersAdmin, column1, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersAdminRow{}
	for rows.Next() {
		var i ListUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users SET
    username   = COALESCE(NULLIF($1, ''), username),
    email      = COALESCE(NULLIF($2, ''), email),
    updated_at = NOW()
WHERE id = $3
`

func (q *Queries) UpdateUserProfile(ctx context.Context, column1 interface{}, column2 interface{}, iD string) error {
	_, err := q.db.Exec(ctx, updateUserProfile, column1, column2, iD)
	return err
}
